project:
  type: website
  output-dir: docs

website:
  favicon: media/flower1.svg
  navbar:
    title: "Sophia Gibson" # this is the website title as it appears in the top left corner -- clicking on this will jump you back to your landing page from where ever you are
    right: # align navbar items to the right/left/center
      - href: index.qmd
        text: Home # use 'text' option to update the name as you want it to appear in your navbar
      - href: media/cv.pdf
        text: CV
      - about.qmd
      - icon: github # add icons that link to social media, etc.
        href: https://github.com/sophia-gibson

format:
  html:
    theme: quartz
    css: styles.css
    toc: true



